// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRL6Yh9MYplIDQIM5jcPcAeov0TJZJgQ',
    appId: '1:357591239740:web:8fc2f7a102d9cd29998739',
    messagingSenderId: '357591239740',
    projectId: 'reboot-office',
    authDomain: 'reboot-office.firebaseapp.com',
    storageBucket: 'reboot-office.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQH13voPY-JoB5uC_h_Cfg1Uu3xE9CMPw',
    appId: '1:357591239740:android:6476498236d2cb13998739',
    messagingSenderId: '357591239740',
    projectId: 'reboot-office',
    storageBucket: 'reboot-office.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Fi9So_4metb4tTzVj_oxrqHqbYtq474',
    appId: '1:357591239740:ios:d69bf193ed3285e5998739',
    messagingSenderId: '357591239740',
    projectId: 'reboot-office',
    storageBucket: 'reboot-office.firebasestorage.app',
    iosBundleId: 'com.kyujin.rebootOffice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Fi9So_4metb4tTzVj_oxrqHqbYtq474',
    appId: '1:357591239740:ios:0b717613de8e9916998739',
    messagingSenderId: '357591239740',
    projectId: 'reboot-office',
    storageBucket: 'reboot-office.firebasestorage.app',
    iosBundleId: 'com.earthus.rebootOffice.rebootOffice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRL6Yh9MYplIDQIM5jcPcAeov0TJZJgQ',
    appId: '1:357591239740:web:4f03dca563b28e4e998739',
    messagingSenderId: '357591239740',
    projectId: 'reboot-office',
    authDomain: 'reboot-office.firebaseapp.com',
    storageBucket: 'reboot-office.firebasestorage.app',
  );
}
